# Site settings
title: Jason's Blog
subtitle: A stochastic thought repository
description: Personal blog of Jason Graham
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jason.the-graham.com"

permalink: /:year/:month/:day/:title/

# Jekyll Location Settings
source: ./_source
destination: ./_site
layouts: ./_layouts
data_source: ./_data
plugins: ./_plugins

# Conversion
highlighter: pygments

# Build settings
markdown: kramdown
sass:
    style: :compressed
    sass_dir: ./_sass
    cache_location: /tmp/sass-cache
